### ISSUE TITLE
Linux&Docker 채점

### ISSUE THREAD

**Issue by hengyinayo** [C-limlim/Ybigta_assignment#1]
![101_5516a02617ec7_2133](https://github.com/C-limlim/Ybigta_assignment/assets/90566079/02461d04-245e-4401-b0e3-4307687b20b9)
과제 열심히 해주셔서 정말 감사합니다!
수고 많으셨어요! 남은 교육세션 홧팅!

**Comment by C-limlim** [comment]
넹~~ 감사합니당 ^^~~

**Comment by C-limlim** [comment]
넹~~ 감사합니당 ~~ ^^
